export const Types = Object.freeze({
  ADD_WORKSPACES: 'ADD_WORKSPACES',
  ADD_WORKSPACE_TEMPLATES: 'ADD_WORKSPACE_TEMPLATES',
  ADD_WORKSPACE: 'ADD_WORKSPACE',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
  REMOVE_WORKSPACE: 'REMOVE_WORKSPACE',

  SET_TEMPLATES: 'SET_TEMPLATES',
  ADD_TEMPLATE: 'ADD_TEMPLATE',
  UPDATE_TEMPLATE: 'UPDATE_TEMPLATE',
  REMOVE_TEMPLATE: 'REMOVE_TEMPLATE',

  SET_PUBLIC_THEMES: 'SET_PUBLIC_THEMES',
  SET_USER_THEMES: 'SET_USER_THEMES',
  CREATE_THEME: 'CREATE_THEME',
  UPDATE_THEME: 'UPDATE_THEME',
  REMOVE_THEME: 'REMOVE_THEME',

  SET_FORMS: 'SET_FORMS',
  CREATE_FORM: 'CREATE_FORM',
  REMOVE_FORM: 'REMOVE_FORM',

  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  UPDATE_USER: 'UPDATE_USER',

  SET_ERRORS: 'SET_ERRORS',
  REMOVE_ERRORS: 'REMOVE_ERRORS',
});
