export const Types = Object.freeze({
  SET_WORKSPACES: 'SET_WORKSPACES',
  CREATE_WORKSPACE: 'CREATE_WORKSPACE',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
  REMOVE_WORKSPACE: 'REMOVE_WORKSPACE',

  SET_TEMPLATES: 'SET_TEMPLATES',
  CREATE_TEMPLATE: 'CREATE_TEMPLATE',
  UPDATE_TEMPLATE: 'UPDATE_TEMPLATE',
  REMOVE_TEMPLATE: 'REMOVE_TEMPLATE',

  SET_PUBLIC_THEMES: 'SET_PUBLIC_THEMES',
  SET_USER_THEMES: 'SET_USER_THEMES',
  CREATE_THEME: 'CREATE_THEME',
  UPDATE_THEME: 'UPDATE_THEME',
  REMOVE_THEME: 'REMOVE_THEME',

  SET_FORMS: 'SET_FORMS',
  CREATE_FORM: 'CREATE_FORM',
  REMOVE_FORM: 'REMOVE_FORM',

  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  UPDATE_USER: 'UPDATE_USER',
});
